<!-- Dynamics - Code generated by CtrlPanel V1-0 -->

<?php
	// Load objects
	/// Page title, can change

	/// Translation
	//// cf. uiTop

	/// Loading Ressources
	$all['r']['str'] = file_get_contents('./objects/ressources.json');
	$all['r'] = json_decode(
		$all['r']['str'],
		associative: true,
		flags: JSON_THROW_ON_ERROR);
	/// Loading Buildings
	$all['b']['str'] = file_get_contents('./objects/buildings.json');
	$all['b'] = json_decode(
		$all['b']['str'],
		associative: true,
		flags: JSON_THROW_ON_ERROR);
	
	/*
	echo "<pre>";
	print_r($all);
	echo "</pre>";
	*/
	
	// Load planet
	if (empty($_SESSION[name])) {
		$page_title .= " - New";
		/* Here, Id must be linked to the correct Name
		 To be aware: SESSION, key is NAME; DB, index is ID */
		
		$SQL["sel"]["planet_info"] = 'SELECT * FROM planet_info WHERE planet_id='.id.';';
		$planet_info_db = DB->fetch($conn_elems, $SQL["sel"]["planet_info"]);
		
		if ($planet_info_db === "lol") {
			/// Load from database if exists
			
			
		} else {
			/// Create planet if not exists (DEBUG: In future, planet will be generated by discovering them)
			$page_title .= " *Debug*";
			//// Debug Test initialization (rn c {r1, r2, r2} and rnk = key)
            $_SESSION[name]['info']['type'] = 'planet';
            $_SESSION[name]['info']['id'] = id;
            $_SESSION[name]['info']['name'] = name;
            $_SESSION[name]['info']['global_name'] = global_name;
            $_SESSION[name]['info']['local_name'] = local_name;
            ///// Ressources
			foreach ($all['r'] as $rnk => $rn) {
				if ($rnk == 'r2') {
                    foreach ($rn as $rk => $r) {
                        $_SESSION[name]['r'][$rnk][$rk] = [];
                    }
                } else {
                    foreach ($rn as $rk => $r) {
                        $_SESSION[name]['r'][$rnk][$rk] = 0;
                    }
                }
            ///// Buildings
			} foreach ($all['b'] as $bk => $b) {
				$_SESSION[name]['b'][$bk] = [];				
			}
			
			//// Debug Test Database port
			
			//// Debug powers
			
			
		}
	}
	
	/*
	echo "<pre>";
	print_r($_SESSION);
	echo "</pre>";
	*/
	
	/// Load from session
	$SS = $_SESSION; 				# Saved session, before update by production (mostly to calc evolution)
	$rs = $_SESSION[name]['r']; 	# Ressources
	$tb = []; 						# To be build
	$bs = $_SESSION[name]['b']; 	# Buildings
	
?>

<div class="ctnr-planet" id="ctnr-ui-game">


    <div class="pnl-folder pnl-sup-tl" id="main-folder-1">
        <div class="head">
            <div class="ctnr-btn-fold1">
                <button class="btn-fold" id="folder-1">O</button>
            </div>
            <div class="ctnr-h-fold1">
                <h2 class="ttl1">Building</h2>
            </div>
        </div>
        <hr>
        <div class="ctnr-content">
            <div class="content">
				<!-- Window 1 - Builds -->
                <table id="table-build" class="table-build1">
                    <tr>
                        <th>Name</th>
                        <th></th>
                        <th>Surface (units)</th>
                        <th></th>

                    </tr>
                    <?php $iid = 0;
                        foreach ($bs as $bname => $bProds):
                            $iid++;
                            $bValSum = 0;
                            foreach ($bProds as $bProdName => $bProdVal) {
                                ///// Sum of the buildings of the array [[n1, "Prod1"], [n2, "Prod2"], ...]
                                $bValSum += $bProdVal;
                            }
                    ?>
                    <tr>
                        <td class="label-itemKey1"><?= $all['b'][$bname]['name'][$lang]; ?> : </td>
                        <td id="bp<?=$iid?>" class="label-itemPlus"><button max="5" class="btn-incr btn-plus1">+</button></td>
                        <td class="label-itemValue1"><?= $bValSum ?></td>
                        <td id="bm<?=$iid?>" class="label-itemMinus"><button max="2" class="btn-incr btn-minus1">-</button></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>

        </div>

    </div>

    <div class="pnl-folder pnl-sup-bl" id="main-folder-2">
        <div class="head">
            <div class="ctnr-btn-fold1">
                <button class="btn-fold" id="folder-2">O</button>
            </div>
            <div class="ctnr-h-fold1">
                <h2 class="ttl1" >Stockpile</h2>
            </div>
        </div>
        <hr>
        <div class="ctnr-content">
            <div class="content">
                <table class="table-build1">
                    <tr>
                        <th>Level</th>
                        <th>
                            <table class="table-build1">
                                <tr>
                                    <th>Ressource</th>
                                    <th>Quantity (units)</th>
                                    <th>Evolution (units)</th>
                                </tr>
                            </table>
                        </th>
                    </tr>
                    <?php foreach ($rs as $rnk => $rn): ?>
                    <tr>
                        <td class=""><?= $rnk ?></td>
                        <td>
                            <table class="table-build1">
                                <?php foreach ($rn as $rname => $rval): 
                                    
                                    if (gettype($rval) === 'array') { ///// R2 ressources, multiple sources
                                        $rValSum = 0;
                                        foreach ($rval as $rSrcName => $rSrcVal) {
                                            ///// Sum of the r2 of the array [[n1, "Prod1"], [n2, "Prod2"], ...]
                                            $rValSum += $rSrcVal;
                                        }
                                        $rval = $rValSum;
                                    }
                                ?>
                                <tr>
                                    <td class="label-itemKey1"><?= $all['r'][$rnk][$rname]['name'][$lang]; ?> : </td>
                                    <td class="label-itemValue1"><?= $rval ?></td>
                                    <td class="label-itemEvo"><?= "+0%" ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                        </td>
                    </tr>
                    <?php endforeach; ?>

                </table>

            </div>

        </div>

    </div>

    <div class="pnl-folder pnl-sup-br" id="main-folder-3">
        <div class="head">
            <div class="ctnr-btn-fold1">
                <button class="btn-fold" id="folder-3">O</button>
            </div>
            <div class="ctnr-h-fold1">
                <h2 class="ttl1">Info</h2>
            </div>
        </div>
        <hr>
        <div class="ctnr-content">
            <div class="content">
                <?php
					echo "Planet info WIP";
				?>


            </div>
        </div>

    </div>

</div>
