
<!-- Dynamics - Code generated by CtrlPanel V1-0 -->

<?php
	// Load objects
	/// Page title, can change

	
	/// Loading Ressources
	$all['r']['str'] = file_get_contents('./objects/ressources.json');
	$all['r'] = json_decode(
		$all['r']['str'],
		associative: true,
		flags: JSON_THROW_ON_ERROR);
	/// Loading Buildings
	$all['b']['str'] = file_get_contents('./objects/buildings.json');
	$all['b'] = json_decode(
		$all['b']['str'],
		associative: true,
		flags: JSON_THROW_ON_ERROR);
	
	/*
	echo "<pre>";
	print_r($all);
	echo "</pre>";
	*/
	
	// Load planet
	if (empty($_SESSION[name])) {
		$page_title .= " - New";
		/* Here, Id must be linked to the correct Name
		 To be aware: SESSION, key is NAME; DB, index is ID */
		
		$SQL["sel"]["planet_info"] = 'SELECT * FROM planet_info WHERE planet_id='.id.';';
		$planet_info_db = DB->fetch($conn_elems, $SQL["sel"]["planet_info"]);
		
		if ($planet_info_db === "lol") {
			/// Load from database if exists
			
			
		} else {
			/// Create planet if not exists (DEBUG: In future, planet will be generated by discovering them)
			$page_title .= " *Debug*";
			//// Debug Test initialization (rn c {r1, r2, r2} and rnk = key)
			foreach ($all['r'] as $rnk => $rn) {
				foreach ($rn as $rk => $r) {
					$_SESSION[name]['r'][$rnk][$rk] = 0;
				}
			} foreach ($all['b'] as $bk => $b) {
				$_SESSION[name]['b'][$bk] = 0;				
			}
			
			//// Debug Test Database port
			
			//// Debug powers
			$_SESSION[name]['r']['r1']['iron'] += 15;
			
			
		}
	}
	
	/*
	echo "<pre>";
	print_r($_SESSION);
	echo "</pre>";
	*/
	
	/// Load from session
	$SS = $_SESSION; 				# Saved session, before update by production (mostly to calc evolution)
	$rs = $_SESSION[name]['r']; 	# Ressources
	$tb = []; 						# To be build
	$bs = $_SESSION[name]['b']; 	# Buildings
	
	
?>

<div class="ctnr-planet" id="ctnr-ui-game">
	
	
	<div class="pnl-folder pnl-sup-tl" id="main-folder-1">
		<div class="head">
			<div class="ctnr-btn-fold1">
				<button class="btn-fold" id="folder-1">O</button>
			</div>
			<div class="ctnr-h-fold1">
				<h2>Building</h2>
			</div>
		</div>
		<hr>
		<div class="ctnr-content">
			<div class="content">
				<table>
				<?php foreach ($bs as $bname => $bval): ?>
					<tr>
						<td class="label-itemKey1"><?= $bname ?> : </td>
						<td><button class="btn-incr btn-plus1">+</button></td>
						<td class="label-itemValue1"><?= $bval ?></td>
						<td><button class="btn-incr btn-minus1">-</button></td>
					</tr>
				<?php endforeach; ?>
				</table>
			</div>
		
		</div>

	</div>
	
	<div class="pnl-folder pnl-sup-bl" id="main-folder-2">
		<div class="head">
			<div class="ctnr-btn-fold1">
				<button class="btn-fold" id="folder-2">O</button>
			</div>
			<div class="ctnr-h-fold1">
				<h2>Stockpile</h2>
			</div>
		</div>
		<hr>
		<div class="ctnr-content">
			<div class="content">
				<table>
				<?php foreach ($rs as $rnk => $rn): ?>
					<tr><th><?= $rnk ?></th>
					<td><table>
					<?php foreach ($rn as $rname => $rval): ?>
						<tr>
							<td class="label-itemKey1"><?= $rname ?> : </td>
							<td class="label-itemValue1"><?= $rval ?></td>
							<td class="label-itemEvo">V</td>
						</tr>
					<?php endforeach; ?>
					</table></td></tr>
				<?php endforeach; ?>
				</table>
				
			</div>
		
		</div>

	</div>
	
	<div class="pnl-folder pnl-sup-br" id="main-folder-3">
		<div class="head">
			<div class="ctnr-btn-fold1">
				<button class="btn-fold" id="folder-3">O</button>
			</div>
			<div class="ctnr-h-fold1">
				<h2>Info</h2>
			</div>
		</div>
		<hr>
		<div class="ctnr-content">
			<div class="content">
				
		
			
			</div>
		</div>

	</div>
	








</div>

<?php session_write_close() ?>