<?php 
  declare(strict_types=1);
  
  echo "<!-- Dynamics - Code generated by CtrlPanel V1-0 -->";
  // Load objects
  // Page title, can change

  // Translation
  // cf. uiTop

  // Loading Object. cf. Loader top
  
  /*
  echo "<pre>";
  print_r($all);
  echo "</pre>";
  */
  
  // Try to load planet from session.
  $planet_number = 3; // defini le nb de planetes
  if (empty($_SESSION[name])) {
    $page_title .= " - New";
    /* Here, Id must be linked to the correct Name
     To be aware: SESSION, key is NAME; DB, index is ID */
    
    $SQL["sel"]["planet_info"] = 'SELECT * FROM planet_info WHERE planet_id='.id.';';
    $planet_info_db = DB->fetch($conn_elems, $SQL["sel"]["planet_info"]);
    
    if ($planet_info_db === "lol") {
      // Load from database if exists, and not in session.
      
      
    } else {
      // Create planet if dont exists 
      // (DEBUG: In future, planet will be generated by discovering them by separate planet gen.)
      $page_title .= " *Debug*";
      $_SESSION[name]['info']['type'] = type;
      $_SESSION[name]['info']['id'] = id;
      $_SESSION[name]['info']['name'] = name;
      $_SESSION[name]['info']['global_name'] = global_name;
      $_SESSION[name]['info']['local_name'] = local_name;
      // Ressources
      foreach ($all['r'] as $ressource_group => $ressources_in_group) {
        if ($ressource_group == 'r2') {
          foreach ($ressources_in_group as $ressource_name => $ressource_quantity) {
            $_SESSION[name]['r'][$ressource_group][$ressource_name] = [];
          }
        } else {
          foreach ($ressources_in_group as $ressource_name => $ressource_quantity) {
            $_SESSION[name]['r'][$ressource_group][$ressource_name] = 0;
          }
        }
      // Create all buildings templates (building key => buidling value)
      } foreach ($all['b'] as $build_name => $build_data) {
        // Init default value
        $_SESSION[name]['b'][$build_name]['undefined'] = 0;
        // Croiser avec le JSON, verifier que toutes les production sont initialisées
        if ($build_data['production'] !== []) {
          foreach ($build_data['production'] as $production_name => $production) {
            // Production output is excpected ressource to be produced.
            $_SESSION[name]['b'][$build_name][$production_name] = 0;
          }
        }		
      }
      // Debug Test Database port
      
      // Debug powers
      
      
    }
  }
  
  /*
  echo "<pre>";
  print_r($_SESSION);
  echo "</pre>";
  */
  
  // Load from session
  $saved_session = $_SESSION;
  $session_ressource = $_SESSION[name]['r']; 	
  $build_queue = []; 						  
  $session_builds = $_SESSION[name]['b']; 	
  
?>

<script>
  // Rend accesible le nb de planetes au fichier js.
  window.nbPlanet = <?php echo $planet_number; ?>;  
</script>

<div class="ctnr-planet" id="ctnr-ui-game">

  <!-- DATA - Intel on the planet -->
   <select id="data-main" class="data">
    <option id="data-type" value="<?=type?>"></option>
    <option id="data-id"   value="<?=id?>"  ></option>
    <option id="data-name" value="<?=name?>"></option>
    <option id="data-global-name" value="<?=global_name?>"></option>
    <option id="data-local-name"  value="<?=local_name?>" ></option>
  </select>

  <!-- GAME -->
  <div class="pnl-folder pnl-sup-tl" id="main-folder-1">
    <div class="head">
      <div class="ctnr-btn-fold1">
        <button class="btn-fold" id="folder-1">O</button>
      </div>
      <div class="ctnr-h-fold1">
        <h2 class="ttl1">Building</h2>
      </div>
    </div>
    <hr>
    <div class="ctnr-content">
      <div class="content">
        <!-- Window 1 - Builds -->
        <table id="table-build" class="table-build1">
          <thead>
            <tr> 
              <th></th>
              <th>Name</th>
              <th>Surface (units)</th>
            </tr>
          </thead>
          <tbody>
            <?php 
              $iid = 0;
              // Foreach buildings
              foreach ($session_builds as $build_name => $build_productions): 
                $iid++;
                $bValSum = 0;
                foreach ($build_productions as $build_production_name => $build_production_value) {
                  // Sum of the buildings of the array [[n1, "Prod1"], [n2, "Prod2"], ...]
                  $bValSum += $build_production_value;
                }
            ?>
                <tr class="line-item-main">
                  <td>
                    <button id="btn-fold-item<?=$iid;?>" class="btn-fold-item">*</button>
                  </td>
                  <td class="label-itemKey1"><?= $all['b'][$build_name]['name'][$lang];?> : </td>
                  <td id="label-itemVal1-<?=$iid?>" class="label-itemValue1">
                    <span 
                      id="inp-building-itemValue1-<?=$build_name;?>" 
                      class="inp-numb1 itemValue1" 
                      building="<?=$build_name;?>" 
                      name="fBuild_<?=name?>_<?=$build_name?>"
                    >
                      <?= $bValSum ?>
                    </span>
                  </td>
                </tr>
                <!-- Production des batiments -->
                <tr id="targetOf-btn-fold-item<?=$iid;?>" class="ctnr-fold-item-details" style="display: none;">
                  <td colspan="3">
                    <table id="table-building-prods" class="table-build1">
                    <?php foreach ($all['b'][$build_name]['production'] as $production_name => $production): ?>
                      <tr id="targetOf-btn-fold-item<?=$build_name."-".$build_production_name?>" class="line-fold-building-production">
                      <!-- Specialized production -->
                        <td><?= $production_name ?></td>
                        <td><?= $production[0] ?> turns</td>
                        <td><?php
                          $production_cost = "";
                          foreach ($production[1] as $production_cost_item => $production_cost_count) {
                            $production_cost .= $production_cost_count." ".$production_cost_item." ";
                          } 
                          echo $production_cost;
                        ?></td>
                        <td>
                          <?php
                            $production_output = "";
                            foreach ($production[2] as $production_output_item => $production_output_count) {
                              $production_output .= $production_output_count. " ".$production_output_item." ";
                            }
                            echo $production_output;
                          ?>
                        </td>
                        
                        
                        <!-- Building field -->
                        <td>
                          <input 
                            id="inp-building-production-<?= $build_name ?>-<?= $production_name; ?>" 
                            class="inp-numb2 itemValue1" 
                            building="<?= $build_name; ?>" 
                            prodution="<?= $production_name; ?>" 
                            type="number" 
                            name="fBuild_<?= name; ?>_<?= $build_name; ?>_<?= $production_name; ?>" 
                            value="<?= $build_productions[$production_name]; ?>" 
                          />
                        </td>
                      </tr>
                    <?php endforeach; ?>
                    </table>
                  </td>
                </tr>
            <?php 
              endforeach; 
            ?>
          </tbody>
        </table>
      </div>

    </div>

  </div>

  <div class="pnl-folder pnl-sup-bl" id="main-folder-2">
    <div class="head">
      <div class="ctnr-btn-fold1">
        <button class="btn-fold" id="folder-2">O</button>
      </div>
      <div class="ctnr-h-fold1">
        <h2 class="ttl1" >Stockpile</h2>
      </div>
    </div>
    <hr>
    <div class="ctnr-content">
      <div class="content">
        <table class="table-build1">
          <tr>
            <th>Level</th>
            <th>
              <table class="table-build1">
                <tr>
                  <th>Ressource</th>
                  <th>Quantity (units)</th>
                  <th>Evolution (units)</th>
                </tr>
              </table>
            </th>
          </tr>
          <?php foreach ($session_ressource as $ressource_group => $ressources_in_group): ?>
          <tr>
            <td class="">
              <?= $ressource_group ?>
            </td>
            <td>
              <table class="table-build1">
                <?php $iid = 0;
                // Foreach ressources
                foreach ($ressources_in_group as $ressource_name => $ressource_value):   
                  $iid++;
                  if (gettype($ressource_value) === 'array') { 
                    // R2 ressources, multiple sources
                    $ressource_value_sum = 0;
                    foreach ($ressource_value as $source_name => $source_value) {
                      // Sum of the r2 of the array [[n1, "Prod1"], [n2, "Prod2"], ...]
                      $ressource_value_sum += $source_value;
                    }
                    $ressource_value = (string) $ressource_value_sum;
                  }
                ?>
                <tr>
                  <td id="label-itemKey1-<?=$iid?>"   class="label-itemKey1">
                    <?= $all['r'][$ressource_group][$ressource_name]['name'][$lang]; ?> : 
                  </td>
                  <td id="label-itemValue1-<?=$iid?>" class="label-itemValue1">
                    <?= $ressource_value ?>
                  </td>
                  <td id="label-itemEvo-<?=$iid?>"  class="label-itemEvo">
                    <?= "+0%" ?>
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            </td>
          </tr>
          <?php endforeach; ?>

        </table>

      </div>

    </div>

  </div>

  <div class="pnl-folder pnl-sup-br" id="main-folder-3">
    <div class="head">
      <div class="ctnr-btn-fold1">
        <button class="btn-fold" id="folder-3">O</button>
      </div>
      <div class="ctnr-h-fold1">
        <h2 class="ttl1">Info</h2>
      </div>
    </div>
    <hr>
    <div class="ctnr-content">
      <div class="content">
        <?php   // Planet intel
          echo "Planet info WIP";
        ?>


      </div>
    </div>

  </div>

</div>
