<!-- Dynamics - SOLAR SYSTEM: Code generated by CtrlPanel V1-0 -->
 <?php
	include_once "./php/common.php";

	// $db_credit_elems = ["train2", "root", "1", ];
	$conn_elems = DB->connect("nm_elems", [CONN_CREDITS_HOST, CONN_CREDITS_USER, CONN_CREDITS_PWD]);
	$_SESSION['conn']['elems'] = $conn_elems;
	// $db_credit_const = ["train2", "root", "1", "nm_const"];
	$conn_const = DB->connect("nm_const", [CONN_CREDITS_HOST, CONN_CREDITS_USER, CONN_CREDITS_PWD]);
	$_SESSION['conn']['const'] = $conn_const;

	// Select all planets
	$SQL["sel_elems"] = "SELECT * FROM all_index";
	$elem_info = mysqli_query($conn_elems, $SQL["sel_elems"]);
	$elem_info = mysqli_fetch_all($elem_info, MYSQLI_ASSOC);



?>
<!DOCTYPE html>
<html>
<head>
	<style>
		
	</style>
	<link rel="stylesheet" href="./css/solarAnimations.css">
	<link rel="stylesheet" href="./css/staryBack.css">
	<link rel="stylesheet" href="./css/general1.css">
	
	
</head>
<body>

	<?php
	?>
	
	<script src="./js/common.js">
	</script>

	<div class="ctnr-main">
		<div id="ctnr-sf" class="ctnr-solar-anims"></div>
		<div id="ctnr-sos" class="ctnr-solar-anims"></div>
		<div id="ctnr-ss" class="ctnr-solar-anims"></div>
	</div>
	<div class="menu-select">
		<div class="titr-menu-select">
			<h3 class="txt-titr-menu-select">Sélectionnez votre destiniation</h3>
		</div>
		<form action="uiTop.php" method="get" class="form-menu-select">
			<select class="select-menu btn-ctr" id="planetSelect" name="fName" onchange="this.form.submit()">
				<option value="Submit">Sélection de la destination</option>
				<!--<option value="Submit">Sun<	/option>-->
			</select>
		</form>
	</div>

	<script src="./js/stars1.js"></script> 
	<script src="./js/animation_menu.js"></script>

</body>
</html>