<!-- Dynamics - SOLAR SYSTEM: Code generated by CtrlPanel V1-0 -->
<!DOCTYPE html>
<html>
<head>
	<style>
		
	</style>
	<link rel="stylesheet" href="./css/solarAnimations.css">
	<link rel="stylesheet" href="./css/staryBack.css">
	<link rel="stylesheet" href="./css/general1.css">
	
	
</head>
<body>

	<?php
		// Calcs




	?>
	
	<script src="./js/common.js">// A enlever</script>

	<div class="ctnr-main">
		<div id="ctnr-sf" class="ctnr-solar-anims"></div>
		<div id="ctnr-sos" class="ctnr-solar-anims"></div>
		<div id="ctnr-ss" class="ctnr-solar-anims"></div>
	</div>

	<script src="./js/stars1.js"></script> 
	<script src="./js/animation_menu.js"></script>

</body>
</html>