<!-- Dynamics - Code generated by CtrlPanel V1-0 -->

<?php
	// Load objects
	/// Page title, can change

	/// Translation
	//// cf. uiTop

	/// Loading Object. cf. Loader top
	
	/*
	echo "<pre>";
	print_r($all);
	echo "</pre>";
	*/
	
	// Load planet
	if (empty($_SESSION[name])) {
		$page_title .= " - New";
		/* Here, Id must be linked to the correct Name
		 To be aware: SESSION, key is NAME; DB, index is ID */
		
		$SQL["sel"]["planet_info"] = 'SELECT * FROM planet_info WHERE planet_id='.id.';';
		$planet_info_db = DB->fetch($conn_elems, $SQL["sel"]["planet_info"]);
		
		if ($planet_info_db === "lol") {
			/// Load from database if exists
			
			
		} else {
			/// Create planet if not exists (DEBUG: In future, planet will be generated by discovering them)
			$page_title .= " *Debug*";
			//// Debug Test initialization (rn c {r1, r2, r2} and rnk = key)
            $_SESSION[name]['info']['type'] = type;
            $_SESSION[name]['info']['id'] = id;
            $_SESSION[name]['info']['name'] = name;
            $_SESSION[name]['info']['global_name'] = global_name;
            $_SESSION[name]['info']['local_name'] = local_name;
            ///// Ressources
			foreach ($all['r'] as $rnk => $rn) {
				if ($rnk == 'r2') {
                    foreach ($rn as $rk => $r) {
                        $_SESSION[name]['r'][$rnk][$rk] = [];
                    }
                } else {
                    foreach ($rn as $rk => $r) {
                        $_SESSION[name]['r'][$rnk][$rk] = 0;
                    }
                }
            ///// Buildings
			} foreach ($all['b'] as $bk => $b) {
				$_SESSION[name]['b'][$bk] = [];				
			}
			
			//// Debug Test Database port
			
			//// Debug powers
			
			
		}
	}
	
	/*
	echo "<pre>";
	print_r($_SESSION);
	echo "</pre>";
	*/
	
	/// Load from session
	$SS = $_SESSION; 				# Saved session, before update by production (mostly to calc evolution)
	$rs = $_SESSION[name]['r']; 	# Ressources
	$tb = []; 						# To be build
	$bs = $_SESSION[name]['b']; 	# Buildings
	
?>

<div class="ctnr-planet" id="ctnr-ui-game">

    <!-- DATA - Intel on the planet -->
     <select id="data-main" class="data">
        <option id="data-type" value="<?=type?>"></option>
        <option id="data-id"   value="<?=id?>"  ></option>
        <option id="data-name" value="<?=name?>"></option>
        <option id="data-global-name" value="<?=global_name?>"></option>
        <option id="data-local-name"  value="<?=local_name?>" ></option>

    </select>

    <!-- GAME -->
    <div class="pnl-folder pnl-sup-tl" id="main-folder-1">
        <div class="head">
            <div class="ctnr-btn-fold1">
                <button class="btn-fold" id="folder-1">O</button>
            </div>
            <div class="ctnr-h-fold1">
                <h2 class="ttl1">Building</h2>
            </div>
        </div>
        <hr>
        <div class="ctnr-content">
            <div class="content">
				<!-- Window 1 - Builds -->
                <table id="table-build" class="table-build1">
                    <tr>   
                        <th></th>
                        <th>Name</th>
                        <!-- <th></th> -->
                        <th>Surface (units)</th>
                        <!-- <th></th> -->

                    </tr>
                    <?php $iid = 0;
                        foreach ($bs as $bname => $bProds): /// Foreach buildings
                            $iid++;
                            $bValSum = 0;
                            foreach ($bProds as $bProdName => $bProdVal) {
                                ///// Sum of the buildings of the array [[n1, "Prod1"], [n2, "Prod2"], ...]
                                $bValSum += $bProdVal;
                            }
                    ?>
                    <tr class="line-item-main">
                        <td>
                            <button id="btn-fold-item<?=$iid;?>" class="btn-fold-item">*</button>
                        </td>
                        <td class="label-itemKey1"><?= $all['b'][$bname]['name'][$lang];?> : </td>
                        <!-- <td id="ctnr-btn-plus<?=$iid?>" class="label-itemPlus">
                            <button id="btn-plus<?=$iid?>" max="5" class="btn-incr btn-plus1">+</button>
                        </td> -->
                        <td id="label-itemVal1-<?=$iid?>" class="label-itemValue1">
                            <input id="inp-building-itemValue1-<?=$bname;?>" class="inp-numb1 itemValue1" building="<?=$bname;?>" type="number" name="fBuild_<?=name?>_<?=$bname?>" value="<?= $bValSum ?>" />
                        </td>
                        <!-- <td id="ctnr-btn-minus<?=$iid?>" class="label-itemMinus">
                            <button id="btn-minus<?=$iid?>" max="2" class="btn-incr btn-minus1">-</button>
                        </td> -->
                    </tr>

                    <?php /// Production des batiments ?>
                        <tbody id="targetOf-btn-fold-item<?=$iid;?>" class="ctnr-fold-item-details" style="display: none;">
                        <?php foreach ($bProds as $bProdName => $bProdVal): ?>
                        <!-- A great line of sub folder -->
                        <tr id="targetOf-btn-fold-item<?=$bname."-".$bProdName?>" class="line-fold-building-production">
                            <td></td>
                            <td><?= $bProdName ?></td>
                            <td>
                                <input id="inp-building-production-<?=$bname."-".$bProdName;?>" class="inp-numb2 itemValue1" building="<?=$bname;?>" prodution="<?= $bProdName;?>" type="number" name="fBuild_<?=name;?>_<?=$bname;?>_<?=$bProdName;?>" value="<?= $bProdVal;?>" />
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        </tbody>
                    
                    <?php endforeach; ?>
                </table>
            </div>

        </div>

    </div>

    <div class="pnl-folder pnl-sup-bl" id="main-folder-2">
        <div class="head">
            <div class="ctnr-btn-fold1">
                <button class="btn-fold" id="folder-2">O</button>
            </div>
            <div class="ctnr-h-fold1">
                <h2 class="ttl1" >Stockpile</h2>
            </div>
        </div>
        <hr>
        <div class="ctnr-content">
            <div class="content">
                <table class="table-build1">
                    <tr>
                        <th>Level</th>
                        <th>
                            <table class="table-build1">
                                <tr>
                                    <th>Ressource</th>
                                    <th>Quantity (units)</th>
                                    <th>Evolution (units)</th>
                                </tr>
                            </table>
                        </th>
                    </tr>
                    <?php foreach ($rs as $rnk => $rn): ?>
                    <tr>
                        <td class=""><?= $rnk ?></td>
                        <td>
                            <table class="table-build1">
                                <?php $iid = 0;
                                foreach ($rn as $rname => $rval):     /// Foreach ressources
                                    $iid++;
                                    if (gettype($rval) === 'array') { ///// R2 ressources, multiple sources
                                        $rValSum = 0;
                                        foreach ($rval as $rSrcName => $rSrcVal) {
                                            ///// Sum of the r2 of the array [[n1, "Prod1"], [n2, "Prod2"], ...]
                                            $rValSum += $rSrcVal;
                                        }
                                        $rval = (string)$rValSum;
                                    }
                                ?>
                                <tr>
                                    <td id="label-itemKey1-<?=$iid?>"   class="label-itemKey1"><?= $all['r'][$rnk][$rname]['name'][$lang]; ?> : </td>
                                    <td id="label-itemValue1-<?=$iid?>" class="label-itemValue1"><?= $rval ?></td>
                                    <td id="label-itemEvo-<?=$iid?>"    class="label-itemEvo"><?= "+0%" ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                        </td>
                    </tr>
                    <?php endforeach; ?>

                </table>

            </div>

        </div>

    </div>

    <div class="pnl-folder pnl-sup-br" id="main-folder-3">
        <div class="head">
            <div class="ctnr-btn-fold1">
                <button class="btn-fold" id="folder-3">O</button>
            </div>
            <div class="ctnr-h-fold1">
                <h2 class="ttl1">Info</h2>
            </div>
        </div>
        <hr>
        <div class="ctnr-content">
            <div class="content">
                <?php   /// Planet intel
					echo "Planet info WIP";
				?>


            </div>
        </div>

    </div>

</div>
